investment-portfolio-tracker:
  target: dev
  outputs:
    dev:
      type: bigquery
      threads: 16
      database: "{{ env_var('project_id') }}"
      schema: "{{ env_var('dataset_name') }}"
      method: service-account
      keyfile: /modeling/gcp_key.json
      location: "{{ env_var('dataset_location', 'EU') }}"
      dataproc_batch: null
